<?php

/**
 * Created by PhpStorm.
 * User: ViviPro
 * Date: 7/31/2016
 * Time: 10:19 PM
 */
class GiaithuongController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->activeModule(__DIR__);
        $this->view->activeMenu = "giaithuong";
    }
    public function indexAction(){
        $config = Configs::findFirst(array("conditions"=>"key='giaithuong'"));
        $this->view->object = $config;
    }


}