<?php

/**
 * Created by PhpStorm.
 * User: ViviPro
 * Date: 7/31/2016
 * Time: 10:19 PM
 */
class CardsAdminController extends ControllerAdminBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->activeModule(__DIR__, "admin");
        $this->view->activeMenu = "cards";
        if(!$this->checkLogin()) return;
    }

    public function indexAction()
    {
        $limit = 50;
        $p = $this->request->get("p");
        if ($p <= 1) $p = 1;
        $cp = ($p - 1) * $limit;
        $query = "1=1 ";
        $data = Cards::find([
            'conditions' => $query,
            'order' => 'id desc',
            'limit' => $limit,
            'offset' => $cp
        ]);
        $this->view->painginfo = Helper::paginginfo(Items::count($query), $limit, $p);
        $this->view->listdata = $data;
    }

    public function formAction(){
        $id = $this->request->get("id");
        if ($this->request->isPost()) {
            try {
                $datapost = Helper::post_to_array("telco,codes,seri");
                if ($id > 0) { // Update
                    $o = Cards::findFirst($id);
                }
                else { //insert
                    $o = new Cards();
                }
                $o->map_object($datapost);
                if ($o->save()) $this->flash->success("X? lı thành công");
                else  $this->flash->error("X? lı th?t b?i");
            } catch (\Exception $e) {
                $this->flash->error($e->getMessage());
            }
            $this->response->redirect("cards-admin/");
        }
        if (!empty($id)) $o = Items::findFirst($id);
        $this->view->object = $o;
    }
    public function deleteAction(){
        $id = $this->request->get("id");
        Cards::findFirst($id)->delete();
        $this->flash->success("Xóa thành công");
        $this->response->redirect("cards-admin/");
        return;
    }


}