<?php

/**
 * Created by PhpStorm.
 * User: ViviPro
 * Date: 7/31/2016
 * Time: 10:19 PM
 */
class TheleAdminController extends ControllerAdminBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->activeModule(__DIR__, "admin");
        $this->view->activeMenu = "thele";
    }

    public function indexAction()
    {
        $gt = Configs::findFirst(array("conditions" => "key='thele'"));
        if($this->request->isPost()){
            if($gt->id<=0) $gt = new Configs();
            $gt->contents = $this->request->getPost("contents");
            $gt->key = "thele";
            $gt->create_at = time();
            $gt->save();
            $this->flash->success("Success");
        }
        $this->view->object = $gt;
    }


}