<?php

/**
 * Created by PhpStorm.
 * User: ViviPro
 * Date: 7/31/2016
 * Time: 10:38 PM
 */
class IndexAdminController extends ControllerAdminBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->activeModule(__DIR__,"admin");
        $this->view->activeMenu = "index";
    }
    public function indexAction(){
        if(!$this->checkLogin()) return;
    }
    public function loginAction(){
        $this->switchLayout("blank");
        global $admin;
        if($this->request->isPost()){
            $username = $this->request->getPost("username");
            $password = $this->request->getPost("password");
            if($username==$admin['username']&&$password==$admin['password']){
                $this->setAuth($admin);
                $this->response->redirect("index-admin/");
            }
            else $this->flash->error("Sai thông tin đăng nhập");
        }
    }
}