<?php

/**
 * Created by PhpStorm.
 * User: ViviPro
 * Date: 7/31/2016
 * Time: 10:19 PM
 */
class ItemsAdminController extends ControllerAdminBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->activeModule(__DIR__, "admin");
        $this->view->activeMenu = "items";
    }

    public function indexAction()
    {

    }


}